# Generated by Django 4.2.11 on 2026-05-22 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateField(verbose_name='추첨일')),
                ('status', models.CharField(choices=[('open', '판매중'), ('closed', '마감'), ('drawn', '추첨완료')], default='open', max_length=10, verbose_name='상태')),
                ('num1', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num3', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num4', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num5', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num6', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('bonus', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('total_sales', models.BigIntegerField(default=0, verbose_name='총 판매액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '회차',
                'verbose_name_plural': '회차 목록',
                'ordering': ['-round_no'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동'), ('mixed', '혼합')], default='manual', max_length=8, verbose_name='유형')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='구매금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일시')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.draw', verbose_name='회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '복권',
                'verbose_name_plural': '복권 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.PositiveSmallIntegerField(verbose_name='게임번호')),
                ('num1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num3', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num4', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('num6', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='lotto.ticket', verbose_name='복권')),
            ],
            options={
                'verbose_name': '번호',
                'verbose_name_plural': '번호 목록',
                'unique_together': {('ticket', 'game_no')},
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='등수')),
                ('prize_amount', models.BigIntegerField(verbose_name='당첨금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.draw', verbose_name='회차')),
                ('ticket_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.ticketnumber', verbose_name='번호')),
            ],
            options={
                'verbose_name': '당첨',
                'verbose_name_plural': '당첨 목록',
            },
        ),
    ]
